name: yachtos_mess
description: "Aplikacja panelu mesy YachtOS Mess"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  http: ^1.1.0
  intl: ^0.18.1
  xml: ^6.3.0
  mqtt_client: ^10.0.0
  libserialport: ^0.3.0+1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  material_design_icons_flutter: ^7.0.7296
  audioplayers: ^5.2.1
  syncfusion_flutter_gauges: ^22.1.34
  google_fonts: ^6.2.1
  geolocator: ^10.1.0
  flutter_svg: ^2.0.7
  
  # Aktualizacja zależności
  typed_data: ^1.3.2
  logging: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
