name: nautineros_mess_tablet
description: "Aplikacja panelu mesy NautinerOS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  http: ^1.1.0
  intl: ^0.18.1
  xml: ^6.3.0
  mqtt_client: ^10.0.0
  libserialport: ^0.3.0+1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  material_design_icons_flutter: ^7.0.7296
  audioplayers: ^5.2.1
  syncfusion_flutter_gauges: ^22.1.34
  google_fonts: ^6.2.1
  
  # Aktualizacja zależności
  typed_data: ^1.3.2
  logging: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
  
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 400
        - asset: assets/fonts/SourceSansPro-It.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldIt.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceSansPro-Light.otf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightIt.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightIt.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SourceSansPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiboldIt.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Black.otf
          weight: 900
        - asset: assets/fonts/SourceSansPro-BlackIt.otf
          weight: 900
          style: italic
